#!/usr/bin/env bash
export DEIS_DOMAIN="deis.dev"
export DEIS_CONTROLLER="http://controller.deis.dev"
export DEISCTL_TUNNEL=tunnel.$DEIS_DOMAIN
export FLEETCTL_TUNNEL=$DEISCTL_TUNNEL
export DEIS_PLATFORM_SSH_PRIVATE_KEY=~/.ssh/deis
export DEIS_SUPERUSER_NAME="drew"
export DEIS_SUPERUSER_PASSWD="deeznuts"
export DEIS_SUPERUSER_EMAIL="drew@blackhole.com"
export DEIS_SUPERUSER_SSH_PUBLIC_KEY=~/.ssh/id_rsa.pub
